// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvjDW8imOkuOHJMdUZ_HrESEjcZiuQZGI',
    appId: '1:473019026826:web:3ea10e41630619e51a4c73',
    messagingSenderId: '473019026826',
    projectId: 'dental-app-ef4ff',
    authDomain: 'dental-app-ef4ff.firebaseapp.com',
    storageBucket: 'dental-app-ef4ff.firebasestorage.app',
    measurementId: 'G-WL17X94MRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-gl1jpZzbTA6St5gLuOnfnIkoV_MHro8',
    appId: '1:473019026826:android:081672d92a929a711a4c73',
    messagingSenderId: '473019026826',
    projectId: 'dental-app-ef4ff',
    storageBucket: 'dental-app-ef4ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDru2t7Idkr3lRsvWkaZYQ1x6bZVGOOhMQ',
    appId: '1:473019026826:ios:b6ab471aeac17f3f1a4c73',
    messagingSenderId: '473019026826',
    projectId: 'dental-app-ef4ff',
    storageBucket: 'dental-app-ef4ff.firebasestorage.app',
    iosBundleId: 'com.karamlyy.dentalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDru2t7Idkr3lRsvWkaZYQ1x6bZVGOOhMQ',
    appId: '1:473019026826:ios:b6ab471aeac17f3f1a4c73',
    messagingSenderId: '473019026826',
    projectId: 'dental-app-ef4ff',
    storageBucket: 'dental-app-ef4ff.firebasestorage.app',
    iosBundleId: 'com.karamlyy.dentalMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvjDW8imOkuOHJMdUZ_HrESEjcZiuQZGI',
    appId: '1:473019026826:web:a316f786fd2fe4231a4c73',
    messagingSenderId: '473019026826',
    projectId: 'dental-app-ef4ff',
    authDomain: 'dental-app-ef4ff.firebaseapp.com',
    storageBucket: 'dental-app-ef4ff.firebasestorage.app',
    measurementId: 'G-ER8WQ444YZ',
  );
}
