// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCguNSvRXic7ncowBc7hKIcsx9jH0-cWz4',
    appId: '1:563932823271:web:59722a8fa55f3c0f5bec42',
    messagingSenderId: '563932823271',
    projectId: 'stomcab',
    authDomain: 'stomcab.firebaseapp.com',
    storageBucket: 'stomcab.firebasestorage.app',
    measurementId: 'G-CM9G9XJ40B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWZkiPiLP73cjOmCHZ4kql32MZxq4NcY',
    appId: '1:563932823271:android:255d2b894a441a685bec42',
    messagingSenderId: '563932823271',
    projectId: 'stomcab',
    storageBucket: 'stomcab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_2aIb_CLuCF79lJdg_fH-GD6unmwoCrs',
    appId: '1:563932823271:ios:a97eac11c255d3485bec42',
    messagingSenderId: '563932823271',
    projectId: 'stomcab',
    storageBucket: 'stomcab.firebasestorage.app',
    iosBundleId: 'com.karamlyy.dentalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_2aIb_CLuCF79lJdg_fH-GD6unmwoCrs',
    appId: '1:563932823271:ios:a97eac11c255d3485bec42',
    messagingSenderId: '563932823271',
    projectId: 'stomcab',
    storageBucket: 'stomcab.firebasestorage.app',
    iosBundleId: 'com.karamlyy.dentalMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCguNSvRXic7ncowBc7hKIcsx9jH0-cWz4',
    appId: '1:563932823271:web:39612d318c03d3d95bec42',
    messagingSenderId: '563932823271',
    projectId: 'stomcab',
    authDomain: 'stomcab.firebaseapp.com',
    storageBucket: 'stomcab.firebasestorage.app',
    measurementId: 'G-DJBVLFNXX1',
  );
}
