// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps (DEV).
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgCLlhQb-aRngQj_7xjWrE8fzmwnon_ZI',
    appId: '1:464019647766:web:e4e7813bcd4c4eea50b437',
    messagingSenderId: '464019647766',
    projectId: 'dental-app-dev-96fda',
    authDomain: 'dental-app-dev-96fda.firebaseapp.com',
    storageBucket: 'dental-app-dev-96fda.firebasestorage.app',
    measurementId: 'G-L7BHMYX112',
  );

  // TODO: Replace with your DEV Firebase project credentials

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSSaK6nvysBLPd5Y36uEu3HMIGLqCagsw',
    appId: '1:464019647766:android:bd1fa54e572a655050b437',
    messagingSenderId: '464019647766',
    projectId: 'dental-app-dev-96fda',
    storageBucket: 'dental-app-dev-96fda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBieXH_d0Gext5crvoOsPeu6iZk76CWHHQ',
    appId: '1:464019647766:ios:92f2d9279e012fe450b437',
    messagingSenderId: '464019647766',
    projectId: 'dental-app-dev-96fda',
    storageBucket: 'dental-app-dev-96fda.firebasestorage.app',
    iosBundleId: 'com.karamlyy.dentalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDru2t7Idkr3lRsvWkaZYQ1x6bZVGOOhMQ',
    appId: '1:473019026826:ios:b6ab471aeac17f3f1a4c73',
    messagingSenderId: '473019026826',
    projectId: 'dental-app-ef4ff-dev',
    storageBucket: 'dental-app-ef4ff-dev.firebasestorage.app',
    iosBundleId: 'com.karamlyy.dentalMobile.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvjDW8imOkuOHJMdUZ_HrESEjcZiuQZGI',
    appId: '1:473019026826:web:a316f786fd2fe4231a4c73',
    messagingSenderId: '473019026826',
    projectId: 'dental-app-ef4ff-dev',
    authDomain: 'dental-app-ef4ff-dev.firebaseapp.com',
    storageBucket: 'dental-app-ef4ff-dev.firebasestorage.app',
    measurementId: 'G-ER8WQ444YZ',
  );
}